Vpop/Controllers/BanhMiController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using Vpop.Data;
using Vpop.Models;
using Vpop.ViewModels;

namespace Vpop.Controllers
{
    public class BanhMiController : Controller
    {
        private OrderDbContext context;

        public BanhMiController(OrderDbContext dbContext)
        {
            context = dbContext;
        }

        internal static Dictionary<string, string> Protein1Choices = new Dictionary<string, string>()
        {
            {"Combo ", "Combo $10"},
            {"Steak ", "Steak $9"},
            {"Shrimp ", "Shrimp $9"},
            {"Fish ", "Fish $9"},
            {"Vegan Beef ", "Vegan Beef $9"}
        };

        internal static Dictionary<string, string> Protein2Choices = new Dictionary<string, string>()
        {
            {"Cold Cut ", "Cold Cut $8"},
            {"Pork ", "Pork $8"},
            {"Chicken ", "Chicken $8"},
            {"Tofu ", "Tofu $8"},
            {"Veggie ", "Veggie $8"}
        };
        public IActionResult Display()
        {
            int orderId = context.Orders.Max(j => j.Id);
            ViewBag.order = context.Orders.Find(orderId);
            ViewBag.message = "Your order has been submitted. Below is your order summary";

            return View();
        }

        [HttpGet]
        public IActionResult Index()
        {
            OrderBanhMiViewModel orderBanhMiViewModel = new OrderBanhMiViewModel(Protein1Choices, Protein2Choices);

            return View(orderBanhMiViewModel);
        }
        [HttpPost]
        public IActionResult Index(OrderBanhMiViewModel orderBanhMiViewModel)
        {
            if (ModelState.IsValid)
            {
                orderBanhMiViewModel.Custname = HttpContext.Session.GetString("CustName"); 
                orderBanhMiViewModel.Price = double.Parse(orderBanhMiViewModel.Item.Split('$')[1]);
                orderBanhMiViewModel.Item = orderBanhMiViewModel.Item.Split('$')[0];

                Order newOrder = new Order
                {
                    Custname = orderBanhMiViewModel.Custname,
                    Item = orderBanhMiViewModel.Item,
                    Price = orderBanhMiViewModel.Price,
                    Category = orderBanhMiViewModel.Category,
                    Currdate = orderBanhMiViewModel.Currdate
                };

                context.Orders.Add(newOrder);
                context.SaveChanges();

                return Redirect("/BanhMi/Display");
            }

            OrderBanhMiViewModel viewModel = new OrderBanhMiViewModel(Protein1Choices, Protein2Choices);
            return View(viewModel);
        }
    }
}

Vpop/Controllers/BowlsController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using Vpop.Data;
using Vpop.Models;
using Vpop.ViewModels;

namespace Vpop.Controllers
{
    public class BowlsController : Controller
    {
        private OrderDbContext context;
        public BowlsController(OrderDbContext dbContext)
        {
            context = dbContext;
        }

        internal static Dictionary<string, string> CategoryChoices = new Dictionary<string, string>()
        {
            {"Salad Bowl", "Salad Bowl"},
            {"Vermicelli Bowl", "Vermicelli Bowl"},
            {"Rice Bowl", "Rice Bowl"}
        };

        internal static Dictionary<string, string> Protein1Choices = new Dictionary<string, string>()
        {
            {"Duck ", "Duck $15"},
            {"Combo ", "Combo $14"},
            {"Shrimp ", "Shrimp $12"},
            {"Steak ", "Steak $12"},
            {"Vegan Beef ", "Vegan Beef $12"},
        };

        internal static Dictionary<string, string> Protein2Choices = new Dictionary<string, string>()
        {
            {"Fish ", "Fish $12"},
            {"Pork ", "Pork $11"},
            {"Chicken ", "Chicken $11"},
            {"Tofu ", "Tofu $11"},
            {"Veggie ", "Veggie $11"}
        };
        public IActionResult Display()
        {
            int orderId = context.Orders.Max(j => j.Id);
            ViewBag.order = context.Orders.Find(orderId);
            ViewBag.message = "Your order has been submitted. Below is your order summary";

            return View();
        }

        [HttpGet]
        public IActionResult Index()
        {
            OrderBowlsViewModel orderBowlsViewModel = new OrderBowlsViewModel(CategoryChoices, Protein1Choices, Protein2Choices);

            return View(orderBowlsViewModel);
        }
        [HttpPost]
        public IActionResult Index(OrderBowlsViewModel orderBowlsViewModel)
        {
            if (ModelState.IsValid)
            {
                orderBowlsViewModel.Custname = HttpContext.Session.GetString("CustName"); 
                orderBowlsViewModel.Price = double.Parse(orderBowlsViewModel.Item.Split('$')[1]);
                orderBowlsViewModel.Item = orderBowlsViewModel.Item.Split('$')[0];

                Order newOrder = new Order
                {
                    Custname = orderBowlsViewModel.Custname,
                    Item = orderBowlsViewModel.Item,
                    Price = orderBowlsViewModel.Price,
                    Category = orderBowlsViewModel.Category,
                    Currdate = orderBowlsViewModel.Currdate
                };

                context.Orders.Add(newOrder);
                context.SaveChanges();

                return Redirect("/Bowls/Display");
            }

            OrderBowlsViewModel viewModel = new OrderBowlsViewModel(CategoryChoices, Protein1Choices, Protein2Choices);
            return View(viewModel);
        }

    }
}

Vpop/Controllers/ReviewController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using Vpop.Data;
using Vpop.Models;

namespace Vpop.Controllers
{
    public class ReviewController : Controller
    {
        private OrderDbContext context;
        public ReviewController(OrderDbContext dbContext)
        {
            context = dbContext;
        }

        //Create a new dictionary to hold the data for a specific customer 
        public static Dictionary<int, Order> OrderCust = new Dictionary<int, Order>();
        public IActionResult Index()
        {
            string custname = HttpContext.Session.GetString("CustName"); 
            List<Order> orders = context.Orders.Where(p => p.Custname == custname).ToList();
            double totalprice = context.Orders.Where(p => p.Custname == custname)
                                              .Sum(p => p.Price);

            ViewBag.title = "Order Summary";
            ViewBag.orders = orders;
            //ViewBag.totalprice = totalprice;
            if (orders.Count > 0)
            {
                ViewBag.custname = orders[0].Custname;
                ViewBag.currdate = orders[0].Currdate;
            }
            return View();
        }
        public IActionResult Determine(int[] cancelOrderIds, int updateOrderId, string cmd)
        {
            if (cmd == "Cancel")
            {
                foreach (int orderId in cancelOrderIds)
                {
                    Order theOrder = context.Orders.Find(orderId);
                    context.Orders.Remove(theOrder);
                }

                context.SaveChanges();

                return Redirect("/Review/Index");
            }
            else if (cmd == "Update")
            {
                ViewBag.Title = "Edit Orders";
                Order order = context.Orders.Find(updateOrderId);
                if (order != null)
                {
                    ViewBag.order = order;

                    if (ViewBag.order.Category == "Banh Mi")
                    {
                        ViewBag.protein1 = BanhMiController.Protein1Choices;
                        ViewBag.protein2 = BanhMiController.Protein2Choices;
                    }
                    else if (ViewBag.order.Category == "Snacks")
                    {
                        ViewBag.snacks1 = SnacksController.Snacks1Choices;
                        ViewBag.snacks2 = SnacksController.Snacks2Choices;
                    }
                    else if (ViewBag.order.Category == "Salad Bowl" || ViewBag.order.Category == "Vermicelli Bowl" || ViewBag.order.Category == "Rice Bowl")
                    {
                        ViewBag.categories = BowlsController.CategoryChoices;
                        ViewBag.proteins1 = BowlsController.Protein1Choices;
                        ViewBag.proteins2 = BowlsController.Protein2Choices;
                    }
                    return View("Edit");
                }
                else
                {
                    return Redirect("/Review/Index");
                }
            }
            else
            {
                string custname = HttpContext.Session.GetString("CustName");
                List<Order> orders = context.Orders.Where(p => p.Custname == custname).ToList();
                double totalprice = context.Orders.Where(p => p.Custname == custname)
                                                  .Sum(p => p.Price);

                ViewBag.title = "Payment Summary";
                ViewBag.orders = orders;
                ViewBag.totalprice = totalprice;
                if (orders.Count > 0)
                {
                    ViewBag.custname = orders[0].Custname;
                    ViewBag.currdate = orders[0].Currdate;
                }
                return View("Checkout");

            }
        }
        public IActionResult Save(int id, string custname, string category, string item, string currdate)
        {
            ViewBag.Title = "Save Orders";
            double priceTemp = double.Parse(item.Split('$')[1]);
            string itemTemp = item.Split('$')[0];
            Order order = context.Orders.Find(id);
            order.Category = category;
            order.Item = itemTemp;
            order.Price = priceTemp;
            order.Currdate = currdate;

            context.Update(order);
            context.SaveChanges();

            ViewBag.order = order;
            ViewBag.message = "Your order has been modified. Below is the revised order";
            return View();
        }
    }
}

Vpop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VpopMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Vpop</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
             <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                 <partial name = "_LoginPartial" />
             </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Vpop - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Vpop/Views/Shared/_MainMenu.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Vpop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Vpop</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="btn btn-primary" asp-controller="BanhMi" asp-action="Index">Order Banh Mi</a>
                        </li>
                        <br>
                        <li class="nav-item">
                            <a class="btn btn-primary" asp-controller="Snacks" asp-action="Index">Order Snacks</a>
                        </li>
                        <li class="nav-item">
                            <a class="btn btn-primary" asp-controller="Bowls" asp-action="Index">Order Bowls</a>
                        </li>
                        <li class="nav-item">
                            <a class="btn btn-primary" asp-controller="Review" asp-action="Index">Review Orders</a>
                        </li>
                        <partial name = "_LoginPartial" />
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Vpop - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>