Vpop/Controllers/SnacksController.cs
using Microsoft.AspNetCore.Mvc;
using Vpop.Data;
using Vpop.Models;
using System.Collections.Generic;
using System.Linq;
using Vpop.ViewModels;
using Microsoft.AspNetCore.Http;

namespace Vpop.Controllers
{
    public class SnacksController : Controller
    {
        private OrderDbContext context;

        public SnacksController(OrderDbContext dbContext)
        {
            context = dbContext;
        }

        internal static Dictionary<string, string> Snacks1Choices = new Dictionary<string, string>()
        {
            {"Snow Crab Rangoons (3) ", "Snow Crab Rangoons (3) $5"},
            {"Snow Crab Rangoons (6) ", "Snow Crab Rangoons (6) $10"},
            {"Vegan Cheese Rolls ", "Vegan Cheese Rolls $4"},
            {"Fried Shrimp Rolls ", "Fried Shrimp Rolls $5"}
        };
        internal static Dictionary<string, string> Snacks2Choices = new Dictionary<string, string>()
        {
            {"Krab Rangoons(3) ", "Krab Rangoons(3) $2.8"},
            {"Krab Rangoons(6) ", "Krab Rangoons(6) $5"},
            {"Veggie Egg Rolls ", "Veggie Egg Rolls $3.5"},
            {"Vietnamese Egg Rolls ", "Vietnamese Egg Rolls $3.5"}
        };
        public IActionResult Display()
        {
            int orderId = context.Orders.Max(j => j.Id);
            ViewBag.order = context.Orders.Find(orderId);
            ViewBag.message = "Your order has been submitted. Below is your order summary";

            return View();
        }

        [HttpGet]
        public IActionResult Index()
        {
            OrderSnacksViewModel orderSnacksViewModel = new OrderSnacksViewModel(Snacks1Choices, Snacks2Choices);

            return View(orderSnacksViewModel);
        }
        [HttpPost]
        public IActionResult Index(OrderSnacksViewModel orderSnacksViewModel)
        {
            if (ModelState.IsValid)
            {
                orderSnacksViewModel.Custname = HttpContext.Session.GetString("CustName"); 
                orderSnacksViewModel.Price = double.Parse(orderSnacksViewModel.Item.Split('$')[1]);
                orderSnacksViewModel.Item = orderSnacksViewModel.Item.Split('$')[0];

                Order newOrder = new Order
                {
                    Custname = orderSnacksViewModel.Custname,
                    Item = orderSnacksViewModel.Item,
                    Price = orderSnacksViewModel.Price,
                    Category = orderSnacksViewModel.Category,
                    Currdate = orderSnacksViewModel.Currdate
                };

                context.Orders.Add(newOrder);
                context.SaveChanges();

                return Redirect("/Snacks/Display");
            }

            OrderSnacksViewModel viewModel = new OrderSnacksViewModel(Snacks1Choices, Snacks2Choices);
            return View(viewModel);
        }
    }
}

Vpop/Views/Snacks/Display.cshtml
@{
    ViewData["Title"] = "Snacks Order Confirmation Page";
    Layout = "_MainMenu";
}

<div>
    <p>@ViewBag.message</p>

    <table class="table">
        <tr>
            <th>
                Order Number
            </th>
            <th>
                Customer Name
            </th>
            <th>
                Category
            </th>
            <th>
                Item
            </th>   
            <th>
                Price
            </th>
             <th>
                Order Date
            </th>   
        </tr>
        <tr>
            <td>@ViewBag.order.Id</td>
            <td>@ViewBag.order.Custname</td>
            <td>@ViewBag.order.Category</td>
            <td>@ViewBag.order.Item</td>
            <td>$@ViewBag.order.Price</td>
            <td>@ViewBag.order.Currdate</td>
        </tr>
    </table>
</div>

Vpop/Views/Snacks/Index.cshtml
@model Vpop.ViewModels.OrderSnacksViewModel;

@{
    ViewData["Title"] = "Snacks Order Page";
    Layout = "_MainMenu";
}

 <h3 style="text-align: center">Snacks Order Form</h3>

 <form asp-controller="Snacks" asp-action="Index" method="post">
      <div>
            <input type="hidden" name="Custname" value=" ">
      </div>
      <div>
          <label>Pick a snack below</label><br />
          <p>
              @foreach (var snack in Model.Snacks1)
              {
                 <input type="radio" name="Item" id="@snack.Key" value="@snack.Value" checked=@(snack.Key == "Vietnamese Egg Rolls ")/>
                 <label for="@snack.Key">@snack.Value</label> 
              }
            <br />
              @foreach (var snack in Model.Snacks2)
              {
                 <input type="radio" name="Item" id="@snack.Key" value="@snack.Value" checked=@(snack.Key == "Vietnamese Egg Rolls ")/>
                 <label for="@snack.Key">@snack.Value</label>   
              }
              <span asp-validation-for="Item"></span>
          </p>
      </div>
       <div>
           <p>
               <input type="hidden" name="Category" value="Snacks">
               <input type="hidden" name="Currdate" value="@DateTime.Now.ToString("MM/dd/yyyy")">
           </p>
       </div>
       <div>
           <p>
              <input type="submit" value="Submit">
           </p>
       </div>
 </form>
 <hr />
 